config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'home#index', as: 'home'
  
  devise_scope :user do
    root 'devise/sessions#new'
  end
  
  resources :reminds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/remind.rb
class Remind < ApplicationRecord
  enum remind_by: [:sms]

  validates :name, presence: true
  validates :delay_days, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable
  after_commit :sms_send, on: :create
  
  private

  def sms_send
    Reminder.new(user: self).perform
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reminds_controller.rb
class RemindsController < ApplicationController
  def index
    @reminds = Remind.all
  end

  def new; end
  
  def edit
    @remind = Remind.find(params[:id])
  end

  def create
    @remind = Remind.new(remind_params)
    if @remind.save
      flash[:success] = t('messages.create.success')
      redirect_to reminds_path
    else
      flash[:error] = t('messages.create.error')
      render 'new'
    end
  end

  def update
    if Remind.find(params[:id]).update(remind_params)
      flash[:success] = t('messages.update.success')
      redirect_to reminds_path
    else
      flash[:error] = t('messages.update.error')
      render 'edit'
    end
  end

  private

  def remind_params
    params.require(:remind).permit(:name, :message_remind, :delay_days)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    added_attrs = [:email, :phone, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<ul class="nav navbar">
  <li class="nav-item text-nowrap">
    <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link small sign-out' do %>
      Sign out
    <% end %>
  </li>
  <li class="nav-item text-nowrap">
    <%= link_to reminds_path, class: 'nav-link small sign-out' do %>
      Remind
    <% end %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HbaoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/reminds/_form.html.erb
<%= simple_form_for remind do |form| %>
  <p>
    <%= form.input :name %>
  </p>
 
  <p>
    <%= form.input :message_remind %>
  </p>

  <p>
    <%= form.input :delay_days %>
  </p>
 
  <p>
    <%= form.button :submit %>
  </p>
<% end %>

app/views/reminds/edit.html.erb
<h1>Edit Remind</h1>
 
<%= render 'form', remind: @remind	 %>
 
<%= link_to 'Back', reminds_path %>

app/views/reminds/index.html.erb
<%= link_to 'New remind', new_remind_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Message</th>
    <th>Days</th>
    <th>Remind By</th>
    <th colspan="5"></th>
  </tr>

  <% @reminds.each do |remind| %>
    <tr>
      <td><%= remind.name %></td>
      <td><%= remind.message_remind %></td>
      <td><%= remind.delay_days %></td>
      <td><%= remind.remind_by %></td>
      <td><%= link_to 'Edit', edit_remind_path(remind), method: :get %></td>
    </tr>
  <% end %>
</table>

app/views/reminds/new.html.erb
<h1>New Remind</h1>
 
<%= render 'form', remind: Remind.new%>
 
<%= link_to 'Back', reminds_path %>